generate_content:
  fields:
    prompt:
      required: true
      selector:
        text:
          multiline: true
    image_filename:
      required: false
      selector:
        object:
    filenames:
      required: false
      selector:
        text:
          multiple: true
add_automation:
  name: "Add Automation"
  description: "Create a new automation from a YAML configuration."
  fields:
    automation_config:
      description: "Full YAML for the automation to add (as text)."
      example: |
        alias: "Turn on living room light at sunset"
        trigger:
          - platform: sun
            event: sunset
        action:
          - service: light.turn_on
            target:
              entity_id: light.living_room_light
get_energy:
  name: "Get Energy Stats"
  description: "Retrieve energy usage statistics."
  fields: {}
